version: "2"

linters:
  default: none
  enable:
    - govet       # includes copylock for mutex copy detection
    - staticcheck # includes gosimple and stylecheck in v2
    - ineffassign
    - unused
    - errcheck

  exclusions:
    presets:
      - std-error-handling

# Run checklocks separately via:
#   go install gvisor.dev/gvisor/tools/checklocks/cmd/checklocks@latest
#   go vet -vettool=$(which checklocks) ./...
