linters:
  enable:
    - govet       # includes copylock for mutex copy detection
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - errcheck

linters-settings:
  govet:
    enable:
      - copylock  # detect copies of sync.Mutex

# Run checklocks separately via:
#   go install gvisor.dev/gvisor/tools/checklocks/cmd/checklocks@latest
#   go vet -vettool=$(which checklocks) ./...
